cTodos en blanco


        accountTile: '',
        breadcrumbsTile: '<div id="kkbrt-breadcrumbs">AQUI EL BREAD</div>',
        carouselTile: ``,
        catMenuTile: ``,
        editAddressTile: ``,
        facetsTile: ``,
        firstAddressTile: ``,
        forgotPasswordTile: ``,
        insertAddressTile: ``,
        loginTile: ``,
        manageAddressBookTile: ``,
        manageCartTile: ``,
        manageEmailTile: ``,
        manageNewsletterTile: ``,
        managePasswordTile: ``,
        managePersonalInfoTile: ``,
        manageWishListTile: ``,
        onePageCheckoutTile: ``,
        orderDetailTile: ``,
        ordersTile: ``,
        popupCartTile: ``,
        popupWishListTile: ``,
        prodDetailTile: ´´,
        productNotificationTile: ``,
        productsTile: ``,
        registerTile: ``,
        reviewsTile: ``,
        searchTile: ``,
        verticalCarouselTile: ``,
        writeReviewTile: ``

